CREATE TABLE [dbo].[email_templates] (
    [eml_key]                     INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [eml_title]                   NVARCHAR (200) NOT NULL,
    [eml_from]                    NVARCHAR (100) NOT NULL,
    [eml_to]                      NVARCHAR (800) NOT NULL,
    [eml_cc]                      NVARCHAR (800) NULL,
    [eml_bcc]                     NVARCHAR (800) NULL,
    [eml_subject]                 NVARCHAR (300) NOT NULL,
    [eml_screen_pop_flag]         BIT            CONSTRAINT [DF_dbo_email_templates_eml_screen_pop_flag] DEFAULT ((0)) NULL,
    [eml_format]                  BIT            CONSTRAINT [DF_dbo_email_templates_eml_format] DEFAULT ((0)) NOT NULL,
    [eml_message]                 NTEXT          NULL,
    [eml_enabled_flag]            BIT            CONSTRAINT [DF_dbo_email_templates_eml_enabled_flag] DEFAULT ((0)) NULL,
    [eml_delete_flag]             BIT            CONSTRAINT [DF_dbo_email_templates_eml_delete_flag] DEFAULT ((0)) NULL,
    [eml_add_user]                NVARCHAR (50)  NULL,
    [eml_add_date]                SMALLDATETIME  NULL,
    [eml_change_user]             NVARCHAR (50)  NULL,
    [eml_change_date]             SMALLDATETIME  NULL,
    [ems_trigger_increment]       SMALLINT       NULL,
    [ems_trigger_increment_type]  SMALLINT       NULL,
    [ems_specdate_increment]      SMALLINT       NULL,
    [ems_specdate_increment_type] SMALLINT       NULL,
    [ems_specdate_before_after]   BIT            NULL,
    [ems_specdate_datefield]      SMALLINT       NULL,
    [ems_cancel_upon_status]      BIT            NULL,
    [ems_email_send]              SMALLINT       NULL,
    [ems_filter_selection]        SMALLINT       NULL,
    [ems_filter_customValue]      NVARCHAR (200) NULL,
    [eml_lock_template]           BIT            NULL,
    [eml_bcc_hidden]              NVARCHAR (800) NULL,
    [eml_attachment_require]      BIT            NULL,
    CONSTRAINT [PK_email_templates] PRIMARY KEY CLUSTERED ([eml_key] ASC)
);

