CREATE TABLE [dbo].[IndividualsTemp] (
    [indv_key]                   BIGINT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [indv_first_name]            NVARCHAR (150) NULL,
    [indv_last_name]             NVARCHAR (150) NULL,
    [indv_gender]                NVARCHAR (10)  NULL,
    [indv_smoking]               BIT            NULL,
    [indv_age]                   BIGINT         NULL,
    [indv_address1]              NVARCHAR (MAX) NULL,
    [indv_address2]              NVARCHAR (MAX) NULL,
    [indv_city]                  NVARCHAR (550) NULL,
    [indv_account_id]            BIGINT         NULL,
    [indv_add_user]              NVARCHAR (50)  NULL,
    [indv_birthday]              SMALLDATETIME  NULL,
    [indv_add_date]              DATETIME       NULL,
    [indv_modified_user]         NVARCHAR (50)  NULL,
    [indv_modified_date]         DATETIME       NULL,
    [indv_active_flag]           BIT            NULL,
    [indv_delete_flag]           BIT            NULL,
    [indv_day_phone]             NVARCHAR (50)  NULL,
    [indv_evening_phone]         NVARCHAR (50)  NULL,
    [indv_cell_phone]            NVARCHAR (50)  NULL,
    [indv_fax_nmbr]              NVARCHAR (50)  NULL,
    [indv_state_Id]              TINYINT        NULL,
    [indv_zipcode]               NVARCHAR (50)  NULL,
    [indv_relation]              NVARCHAR (50)  NULL,
    [indv_notes]                 NVARCHAR (MAX) NULL,
    [indv_email]                 NVARCHAR (50)  NULL,
    [indv_external_reference_id] NVARCHAR (50)  NULL,
    CONSTRAINT [PK_IndividualsTemp] PRIMARY KEY CLUSTERED ([indv_key] ASC)
);

