CREATE TABLE [dbo].[Lead_All_Rows_Condado_3_20130406] (
    [Lead Id]                   BIGINT        NULL,
    [Vehicle 1 Year]            VARCHAR (500) NULL,
    [Vehicle 2 Year]            VARCHAR (500) NULL,
    [Year Home Built]           VARCHAR (500) NULL,
    [Roof Age]                  VARCHAR (500) NULL,
    [Roof Type]                 VARCHAR (500) NULL,
    [Dwelling Type]             VARCHAR (500) NULL,
    [Design Type]               VARCHAR (500) NULL,
    [DL Number]                 VARCHAR (500) NULL,
    [Exterior Wall Type]        VARCHAR (500) NULL,
    [Foundation Type]           VARCHAR (500) NULL,
    [Heating Type]              VARCHAR (500) NULL,
    [Number Bedrooms]           VARCHAR (500) NULL,
    [Number Bathrooms]          VARCHAR (500) NULL,
    [Policy Bound # - Auto]     VARCHAR (500) NULL,
    [Sq Footage]                VARCHAR (500) NULL,
    [Requested Coverage]        VARCHAR (500) NULL,
    [Did We Show Savings Auto?] VARCHAR (500) NULL,
    [Did We Show Savings Home?] VARCHAR (500) NULL,
    [Policy Owner]              VARCHAR (500) NULL,
    [SQ Agent Name]             VARCHAR (500) NULL,
    [Life Agent Phone]          VARCHAR (500) NULL,
    [SQ CS Name]                VARCHAR (500) NULL,
    [SQ CS Phone]               VARCHAR (500) NULL,
    [A - Policy Effective Date] VARCHAR (500) NULL,
    [A - Policy Payment Mode]   VARCHAR (500) NULL,
    [A - Policy Mode Premium]   VARCHAR (500) NULL,
    [A - Policy Mail Date]      VARCHAR (500) NULL,
    [A - Reason For Purchase]   VARCHAR (500) NULL,
    [S - First Name]            VARCHAR (500) NULL,
    [S - Last Name]             VARCHAR (500) NULL,
    [S - Mobile Phone]          VARCHAR (500) NULL,
    [S - Email]                 VARCHAR (500) NULL,
    [Spouse Birthdate]          VARCHAR (500) NULL,
    [S - INF Carrier]           VARCHAR (500) NULL,
    [S - INF Policy #]          VARCHAR (500) NULL,
    [S - INF Annual Premium]    VARCHAR (500) NULL,
    [S - DL #]                  VARCHAR (500) NULL,
    [S - DL State]              VARCHAR (500) NULL,
    [S - Est  Income]           VARCHAR (500) NULL,
    [S - Occupation]            VARCHAR (500) NULL,
    [S - Policy Effective Date] VARCHAR (500) NULL,
    [S - Policy Payment Mode]   VARCHAR (500) NULL,
    [S - CRI Date]              VARCHAR (500) NULL,
    [S - INF Date]              VARCHAR (500) NULL,
    [S - Policy Mail Date]      VARCHAR (500) NULL,
    [S - Policy Mode Premium]   VARCHAR (500) NULL,
    [S - 5 Year MVR]            VARCHAR (500) NULL,
    [S - 3 Year MVR]            VARCHAR (500) NULL,
    [S - DUI MVR]               VARCHAR (500) NULL,
    [A - PMOC]                  VARCHAR (500) NULL,
    [S - PMOC]                  VARCHAR (500) NULL,
    [TA - Action]               VARCHAR (500) NULL,
    [S - Face Amount]           VARCHAR (500) NULL,
    [S - Prefix]                VARCHAR (500) NULL,
    [Keyword]                   VARCHAR (500) NULL,
    [Group]                     VARCHAR (500) NULL
);

