CREATE TABLE [dbo].[Lead_All_Rows_Condado_4_20130406] (
    [Lead Id]                            BIGINT        NULL,
    [A - SQ Lead Status]                 VARCHAR (500) NULL,
    [Transfer Agent]                     VARCHAR (500) NULL,
    [A - Gender]                         VARCHAR (500) NULL,
    [S - Gender]                         VARCHAR (500) NULL,
    [Driver 1 Education]                 VARCHAR (500) NULL,
    [Driver 1 Claim Paid Amount]         VARCHAR (500) NULL,
    [Driver 1 Age Licensed]              VARCHAR (500) NULL,
    [Driver 1 Incident Date]             VARCHAR (500) NULL,
    [Driver 1 Incident Description]      VARCHAR (500) NULL,
    [Driver 1 Incident Type]             VARCHAR (500) NULL,
    [Driver 1 Tickets Accidents Claims?] VARCHAR (500) NULL,
    [Driver 1 DL State]                  VARCHAR (500) NULL,
    [Driver 1 License Status]            VARCHAR (500) NULL,
    [Driver 1 Marital Status]            VARCHAR (500) NULL,
    [Driver 1 Number of Incidents]       VARCHAR (500) NULL,
    [Driver 1 Occupation]                VARCHAR (500) NULL,
    [Driver 1 Policy Years]              VARCHAR (500) NULL,
    [Driver 1 SR22?]                     VARCHAR (500) NULL,
    [Driver 1 Yrs at Residence]          VARCHAR (500) NULL,
    [Driver 1 Yrs in Field]              VARCHAR (500) NULL,
    [Driver 1 Yrs With Company]          VARCHAR (500) NULL,
    [Driver 2 Age Licensed]              VARCHAR (500) NULL,
    [Driver 2 Claim Paid Amount]         VARCHAR (500) NULL,
    [Driver 2 Education]                 VARCHAR (500) NULL,
    [Driver 2 Incident Date]             VARCHAR (500) NULL,
    [Driver 2 Incident Description]      VARCHAR (500) NULL,
    [Driver 2 Incident Type]             VARCHAR (500) NULL,
    [Driver 2 Tickets Accidents Claims?] VARCHAR (500) NULL,
    [Driver 2 DL State]                  VARCHAR (500) NULL,
    [Driver 2 License Status]            VARCHAR (500) NULL,
    [Driver 2 Marital Status]            VARCHAR (500) NULL,
    [Driver 2 Number of Incidents]       VARCHAR (500) NULL,
    [Driver 2 Occupation]                VARCHAR (500) NULL,
    [Driver 2 SR22?]                     VARCHAR (500) NULL,
    [Driver 2 Yrs at Residence]          VARCHAR (500) NULL,
    [Driver 2 Yrs in Field]              VARCHAR (500) NULL,
    [Driver 2 Yrs With Company]          VARCHAR (500) NULL,
    [Liability Limits - Auto]            VARCHAR (500) NULL,
    [Medical Payments - Auto]            VARCHAR (500) NULL,
    [Repossession?]                      VARCHAR (500) NULL,
    [Vehicle 1 Annual Mileage]           VARCHAR (500) NULL,
    [Vehicle 1 Collision Deductible]     VARCHAR (500) NULL,
    [Vehicle 1 Comprehensive Deductible] VARCHAR (500) NULL,
    [Vehicle 1 Sub-Model]                VARCHAR (500) NULL,
    [Vehicle 1 Primary Use]              VARCHAR (500) NULL,
    [Vehicle 1 Security System]          VARCHAR (500) NULL,
    [Vehicle 1 Weekly Commute Days]      VARCHAR (500) NULL,
    [Vehicle 1 Where Parked]             VARCHAR (500) NULL,
    [Vehicle 2 Annual Mileage]           VARCHAR (500) NULL,
    [Vehicle 2 Collision Deductible]     VARCHAR (500) NULL,
    [Vehicle 2 Comprehensive Deductible] VARCHAR (500) NULL,
    [Vehicle 2 Sub-Model]                VARCHAR (500) NULL,
    [Vehicle 2 Primary Use]              VARCHAR (500) NULL,
    [Vehicle 2 Security System]          VARCHAR (500) NULL,
    [Vehicle 2 Weekly Commute Days]      VARCHAR (500) NULL,
    [Vehicle 2 Where Parked]             VARCHAR (500) NULL,
    [Driver 2 Birthdate]                 VARCHAR (500) NULL,
    [Driver 2 First Name]                VARCHAR (500) NULL,
    [Driver 2 Last Name]                 VARCHAR (500) NULL,
    [TA - Action Date]                   VARCHAR (500) NULL,
    [Expected Close Date]                VARCHAR (500) NULL,
    [Do you expect this to close?]       VARCHAR (500) NULL,
    [TA APPT SET]                        VARCHAR (500) NULL,
    [Application Name]                   VARCHAR (500) NULL
);

