CREATE TABLE [dbo].[Lead_All_Rows_Condado_5_20130406] (
    [Lead Id]                              BIGINT        NULL,
    [S - SQ Policy Type]                   VARCHAR (500) NULL,
    [B - Current MONTHLY Premium AUTO]     VARCHAR (500) NULL,
    [B - Current MONTHLY Premium HOME]     VARCHAR (500) NULL,
    [Q - Current MONTHLY Premium AUTO]     VARCHAR (500) NULL,
    [Q - Current MONTHLY Premium HOME]     VARCHAR (500) NULL,
    [B - Current Carrier AUTO]             VARCHAR (500) NULL,
    [B - Current Carrier HOME]             VARCHAR (500) NULL,
    [Q - Current Carrier AUTO]             VARCHAR (500) NULL,
    [Q - Current Carrier HOME]             VARCHAR (500) NULL,
    [B - Did We Increase Coverage? - AUTO] VARCHAR (500) NULL,
    [B - Did We Increase Coverage? HOME]   VARCHAR (500) NULL,
    [AGENT Rating]                         VARCHAR (500) NULL,
    [Best Number to Call]                  VARCHAR (500) NULL,
    [Best Date To Call]                    VARCHAR (500) NULL,
    [Best Time to Call]                    VARCHAR (500) NULL,
    [Owner Button Clicked?]                VARCHAR (500) NULL,
    [QW - State]                           VARCHAR (500) NULL,
    [QW - ID]                              VARCHAR (500) NULL,
    [sh-id]                                VARCHAR (500) NULL,
    [Transfer Agent]                       VARCHAR (500) NULL,
    [COL Transferred Via]                  VARCHAR (500) NULL,
    [Umbrella Quoted -?]                   VARCHAR (500) NULL,
    [FILE NUMBER]                          VARCHAR (500) NULL,
    [SQ Ref Number-Spouse]                 VARCHAR (500) NULL,
    [Ad Variation]                         VARCHAR (500) NULL,
    [Address]                              VARCHAR (500) NULL,
    [Address fields completed ]            VARCHAR (500) NULL,
    [Vehicle 1 VIN]                        VARCHAR (500) NULL,
    [SQ Agent Code]                        VARCHAR (500) NULL,
    [COL Notes]                            VARCHAR (500) NULL,
    [Household Income]                     VARCHAR (500) NULL,
    [RateKick Selected Carrier]            VARCHAR (500) NULL,
    [RateKick Quoted Cost]                 VARCHAR (500) NULL,
    [Missed Transfer?]                     VARCHAR (500) NULL,
    [Test Link]                            VARCHAR (500) NULL,
    [First Edited By]                      VARCHAR (500) NULL,
    [ COL 1st Modified By]                 VARCHAR (500) NULL
);

