CREATE TABLE [dbo].[Lead_All_Rows_Condado_1_20130406_nonotes] (
    [Lead Id]                BIGINT        NULL,
    [1st Named Insured]      VARCHAR (500) NULL,
    [Last Name]              VARCHAR (500) NULL,
    [State]                  VARCHAR (500) NULL,
    [Lead Status]            VARCHAR (500) NULL,
    [Rating]                 VARCHAR (500) NULL,
    [Lead Source]            VARCHAR (500) NULL,
    [Agent]                  VARCHAR (500) NULL,
    [Created Date]           DATETIME      NULL,
    [Time Created]           DATETIME      NULL,
    [Dial]                   BIGINT        NULL,
    [Date Modified]          DATETIME      NULL,
    [Quoted Date Auto]       VARCHAR (500) NULL,
    [Quoted Date Home]       VARCHAR (500) NULL,
    [# of Home Claims]       VARCHAR (50)  NULL,
    [A - 3 Year MVR]         BIGINT        NULL,
    [A - 5 Year MVR]         BIGINT        NULL,
    [A - CRI Date]           DATETIME      NULL,
    [A - DL #]               VARCHAR (500) NULL,
    [A - DL State]           VARCHAR (500) NULL,
    [A - DUI MVR]            BIGINT        NULL,
    [A - Est  Income]        BIGINT        NULL,
    [A - Face Amount]        BIGINT        NULL,
    [A - INF Annual Premium] FLOAT (53)    NULL,
    [A - INF Carrier]        VARCHAR (500) NULL,
    [A - INF Date]           DATETIME      NULL,
    [A - Life Policy ID]     VARCHAR (500) NULL,
    [A-Life Policy Type]     VARCHAR (500) NULL,
    [A - Marital Status]     VARCHAR (500) NULL,
    [A - Occupation]         VARCHAR (500) NULL,
    [Salutation]             VARCHAR (500) NULL,
    [Middle Name]            VARCHAR (500) NULL,
    [Birthdate]              DATETIME      NULL,
    [Company Name]           VARCHAR (500) NULL,
    [Account Number]         VARCHAR (500) NULL,
    [Agent Code*]            VARCHAR (500) NULL,
    [Type]                   VARCHAR (500) NULL,
    [SIC Code]               VARCHAR (500) NULL,
    [Ticker Symbol]          VARCHAR (500) NULL,
    [Ownership]              VARCHAR (500) NULL,
    [Home Phone*]            VARCHAR (500) NULL,
    [--]                     VARCHAR (500) NULL,
    [Other Phone]            VARCHAR (500) NULL,
    [Mobile Phone]           VARCHAR (500) NULL,
    [Fax]                    VARCHAR (500) NULL,
    [Email]                  VARCHAR (500) NULL,
    [Email Opt Out]          VARCHAR (500) NULL,
    [Assistant First Name]   VARCHAR (500) NULL,
    [Assistant Last Name]    VARCHAR (500) NULL,
    [Is address complete?]   VARCHAR (500) NULL,
    [Annual Revenue]         VARCHAR (500) NULL,
    [Employees]              VARCHAR (500) NULL,
    [Website]                VARCHAR (500) NULL,
    [Campaign]               VARCHAR (500) NULL,
    [Created By]             VARCHAR (500) NULL,
    [Title]                  VARCHAR (500) NULL,
    [Address]                VARCHAR (500) NULL,
    [Address 2]              VARCHAR (500) NULL,
    [City]                   VARCHAR (500) NULL,
    [Zip]                    VARCHAR (500) NULL,
    [Billing Country]        VARCHAR (500) NULL,
    [Time Zone]              VARCHAR (500) NULL,
    [Company Size]           VARCHAR (500) NULL,
    [NAICS]                  VARCHAR (500) NULL,
    [NAICS Desc]             VARCHAR (500) NULL,
    [Last Modified By]       VARCHAR (500) NULL,
    [Time Modified]          VARCHAR (500) NULL,
    [Search Engine]          VARCHAR (500) NULL,
    [Keyword]                VARCHAR (500) NULL,
    [Web Offer Type]         VARCHAR (500) NULL,
    [External ID]            VARCHAR (500) NULL,
    [Do Not Call]            VARCHAR (500) NULL,
    [Federal Do Not Call]    VARCHAR (500) NULL,
    [Additional Owners]      VARCHAR (500) NULL,
    [System Identifier]      VARCHAR (500) NULL,
    [Last Dialed By]         VARCHAR (500) NULL,
    [Last Emailed By]        VARCHAR (500) NULL,
    [Last Note Added By]     VARCHAR (500) NULL,
    [Next Event]             VARCHAR (500) NULL,
    [AGENT Appointment Set]  VARCHAR (500) NULL,
    [Inbound]                VARCHAR (500) NULL,
    [NoAns]                  VARCHAR (500) NULL,
    [Appointment]            VARCHAR (500) NULL
);

