CREATE TABLE [dbo].[Lead_All_Rows_Condado_2_20130423] (
    [Lead Id]                                 VARCHAR (500) NULL,
    [Busy]                                    VARCHAR (500) NULL,
    [Message]                                 VARCHAR (500) NULL,
    [Fax]                                     VARCHAR (500) NULL,
    [Email]                                   VARCHAR (500) NULL,
    [Contact]                                 VARCHAR (500) NULL,
    [Correct Contact]                         VARCHAR (500) NULL,
    [Social Message]                          VARCHAR (500) NULL,
    [Close   Sell Date]                       VARCHAR (500) NULL,
    [County]                                  VARCHAR (500) NULL,
    [Current Auto Carrier]                    VARCHAR (500) NULL,
    [Current Home Carrier]                    VARCHAR (500) NULL,
    [Current Auto Premium]                    VARCHAR (500) NULL,
    [Current Home Premium]                    VARCHAR (500) NULL,
    [Current Auto X-Date]                     VARCHAR (500) NULL,
    [Current Home X-Date]                     VARCHAR (500) NULL,
    [Additonal Lead Info]                     VARCHAR (500) NULL,
    [Work Phone]                              VARCHAR (500) NULL,
    [Current Carrier Auto - Lead Info]        VARCHAR (500) NULL,
    [Current Auto X-Date - Lead Info]         VARCHAR (500) NULL,
    [Current Home Carrier - Lead Info]        VARCHAR (500) NULL,
    [Current Home X-Date - Lead Info]         VARCHAR (500) NULL,
    [Credit Self Rating]                      VARCHAR (500) NULL,
    [Vehicle 1 Make]                          VARCHAR (500) NULL,
    [Vehicle 1 Model]                         VARCHAR (500) NULL,
    [Vehicle 2 Make]                          VARCHAR (500) NULL,
    [Vehicle 2 Model]                         VARCHAR (500) NULL,
    [Policy Bound Carrier - Auto]             VARCHAR (500) NULL,
    [Policy Bound Carrier - Home]             VARCHAR (500) NULL,
    [Policy Bound Term - Auto]                VARCHAR (500) NULL,
    [Policy Bound Date - Auto]                VARCHAR (500) NULL,
    [Policy Bound Term- Home]                 VARCHAR (500) NULL,
    [Policy Bound Monthly Premuim - Home]     VARCHAR (500) NULL,
    [Policy Bound Date - Home]                VARCHAR (500) NULL,
    [Policy Bound Monthly Premium - Auto]     VARCHAR (500) NULL,
    [Quoted Carrier - Auto]                   VARCHAR (500) NULL,
    [Quoted Monthly Premium - Auto]           VARCHAR (500) NULL,
    [Quoted Carrier - Home]                   VARCHAR (500) NULL,
    [Quoted Monthly Premium - Home]           VARCHAR (500) NULL,
    [Policy Bound Monthly Premium - Renters]  VARCHAR (500) NULL,
    [Umbrella Policy Bound?]                  VARCHAR (500) NULL,
    [Policy Bound Monthly Premium - Umbrella] VARCHAR (500) NULL,
    [Umbrella Quoted?]                        VARCHAR (500) NULL,
    [Policy Bound Carrier - Renters]          VARCHAR (500) NULL,
    [Policy Bound Carrier - Umbrella]         VARCHAR (500) NULL,
    [DL Number]                               VARCHAR (500) NULL,
    [Policy Bound # - Auto]                   VARCHAR (500) NULL,
    [Policy Bound # - Home]                   VARCHAR (500) NULL,
    [Policy Bound # - Renters]                VARCHAR (500) NULL,
    [Policy Bound # - Umbrella]               VARCHAR (500) NULL
);

