CREATE TABLE [dbo].[Policy_Information] (
    [pol_key]                         BIGINT         IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [pol_individual_id]               BIGINT         NOT NULL,
    [pol_carrier_Id]                  NVARCHAR (MAX) NULL,
    [pol_carrier_Plan]                NVARCHAR (MAX) NOT NULL,
    [pol_guaranteed_issue_reason]     NVARCHAR (MAX) NOT NULL,
    [pol_previous_plan]               NVARCHAR (MAX) NOT NULL,
    [pol_annual_premium]              NVARCHAR (MAX) NOT NULL,
    [pol_issue_date]                  NVARCHAR (MAX) NOT NULL,
    [pol_effective_date]              NVARCHAR (MAX) NOT NULL,
    [pol_fav_key]                     NVARCHAR (MAX) NOT NULL,
    [pol_favkey_sent_to_carrier_date] NVARCHAR (MAX) NOT NULL,
    [pol_cancel_decline_date]         NVARCHAR (MAX) NOT NULL,
    [pol_payment_mode]                NVARCHAR (MAX) NOT NULL,
    [pol_reissue_date]                NVARCHAR (MAX) NOT NULL,
    [pol_medsupp_paid_from_carrier]   NVARCHAR (MAX) NOT NULL,
    [pol_medsupp_commission_amount]   NVARCHAR (MAX) NOT NULL,
    [pol_medsupp_paid_date]           NVARCHAR (MAX) NOT NULL,
    [pol_add_user]                    BIGINT         NULL,
    [pol_add_date]                    DATETIME       NULL,
    [pol_change_user]                 BIGINT         NULL,
    [pol_change_date]                 DATETIME       NULL,
    [Carriers_car_key]                BIGINT         NOT NULL,
    [Plans_Plan_ID]                   BIGINT         NOT NULL,
    CONSTRAINT [PK_Policy_Information] PRIMARY KEY CLUSTERED ([pol_key] ASC),
    CONSTRAINT [FK__Policy_In__Carri__04E4BC85] FOREIGN KEY ([Carriers_car_key]) REFERENCES [dbo].[Carriers] ([car_key]),
    CONSTRAINT [FK__Policy_In__Plans__05D8E0BE] FOREIGN KEY ([Plans_Plan_ID]) REFERENCES [dbo].[Plans] ([Plan_ID])
);

