CREATE TABLE [dbo].[roles] (
    [rol_key]                          INT           IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [rol_acct_priority_view]           INT           NOT NULL,
    [rol_acct_access]                  INT           NOT NULL,
    [rol_acct_reassign]                BIT           CONSTRAINT [DF_Roles_1] DEFAULT ((0)) NOT NULL,
    [rol_acct_delete]                  BIT           CONSTRAINT [DF_Roles_2] DEFAULT ((0)) NOT NULL,
    [rol_acct_attachment]              INT           NOT NULL,
    [rol_click_to_dial]                BIT           NOT NULL,
    [rol_get_a_lead]                   BIT           NOT NULL,
    [rol_arm]                          BIT           NOT NULL,
    [rol_rpt_filter]                   INT           NOT NULL,
    [rol_rpt_cat]                      BIT           NOT NULL,
    [rol_rpt_rdl_map]                  BIT           NOT NULL,
    [rol_rpt_design]                   BIT           NOT NULL,
    [rol_admin_users]                  BIT           NOT NULL,
    [rol_admin_roles]                  BIT           NOT NULL,
    [rol_admin_skills]                 BIT           NOT NULL,
    [rol_admin_campaigns]              BIT           NOT NULL,
    [rol_admin_gal]                    BIT           NOT NULL,
    [rol_admin_act_status]             BIT           NOT NULL,
    [rol_admin_emails]                 BIT           NOT NULL,
    [rol_admin_posts]                  BIT           NOT NULL,
    [rol_admin_prioritization]         BIT           NOT NULL,
    [rol_admin_quick_links]            BIT           NOT NULL,
    [rol_admin_retntions]              BIT           NOT NULL,
    [rol_name]                         NVARCHAR (50) NULL,
    [rol_system_role]                  BIT           CONSTRAINT [DF_Roles_rol_system_role] DEFAULT ((0)) NULL,
    [rol_admin_alerts]                 BIT           CONSTRAINT [DF_Roles_rol_admin_alerts] DEFAULT ((0)) NULL,
    [rol_acct_retention_view]          INT           CONSTRAINT [DF_roles_rol_acct_retention_view] DEFAULT ((0)) NULL,
    [rol_acc_reassigncsr]              BIT           NULL,
    [rol_acc_reassignstatus]           BIT           NULL,
    [rol_acc_reassign_ta]              BIT           NOT NULL,
    [rol_acc_changeownership]          BIT           CONSTRAINT [DF__roles__rol_acc_c__04866080] DEFAULT ((0)) NULL,
    [rol_acc_CampaignOverride]         BIT           CONSTRAINT [DF_roles_rol_acc_CampaignOverride] DEFAULT ((0)) NOT NULL,
    [rol_admin_status_restriction]     BIT           CONSTRAINT [DF_roles_rol_admin_status_restriction] DEFAULT ((0)) NULL,
    [rol_account_status_restriction]   BIT           NULL,
    [rol_admin_manage_duplicate_rules] BIT           CONSTRAINT [DF__roles__rol_admin__0C3BC58A] DEFAULT ((1)) NULL,
    [rol_admin_view_duplicates]        BIT           CONSTRAINT [DF__roles__rol_admin__0D2FE9C3] DEFAULT ((1)) NULL,
    [rol_edit_external_agent]          BIT           NULL,
    [rol_next_acc_settings]            INT           NULL,
    [rol_admin_dashboard]              BIT           CONSTRAINT [DF__roles__rol_admin__286DEFE4] DEFAULT ((0)) NULL,
    [rol_modify_carrier_issue]         BIT           CONSTRAINT [DF__roles__rol_modif__2C3E80C8] DEFAULT ((0)) NULL,
    [rol_dash_type]                    TINYINT       CONSTRAINT [DF__roles__rol_dash___2E26C93A] DEFAULT ((1)) NULL,
    [rol_edit_submit_enroll_dates]     BIT           CONSTRAINT [DF__roles__rol_edit___60B24907] DEFAULT ((0)) NULL,
    [rol_admin_reassignments]          BIT           DEFAULT ((0)) NULL,
    [rol_acct_reassignment_view]       INT           DEFAULT ((0)) NULL,
    [rol_acct_ob]                      BIT           DEFAULT ((0)) NULL,
    [rol_acct_ap]                      BIT           DEFAULT ((0)) NULL,
    [rol_admin_manage_original_user]   BIT           DEFAULT ((0)) NULL,
    CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED ([rol_key] ASC)
);

