CREATE TABLE [dbo].[user_permissions] (
    [usp_key]                          INT              NOT NULL,
    [usp_usr_key]                      UNIQUEIDENTIFIER NOT NULL,
    [usp_rol_key]                      INT              NULL,
    [usp_role_override]                BIT              CONSTRAINT [DF_User_Permissions_usp_role_override] DEFAULT ((0)) NOT NULL,
    [usp_acct_priority_view]           INT              NOT NULL,
    [usp_acct_access]                  INT              NOT NULL,
    [usp_acct_reassign]                BIT              CONSTRAINT [DF_User_Permissions_usp_acct_reassign] DEFAULT ((0)) NOT NULL,
    [usp_acct_delete]                  BIT              CONSTRAINT [DF_User_Permissions_usp_acct_delete] DEFAULT ((0)) NOT NULL,
    [usp_acct_attachment]              INT              NOT NULL,
    [usp_click_to_dial]                BIT              NOT NULL,
    [usp_get_a_lead]                   BIT              NOT NULL,
    [usp_arm]                          BIT              NOT NULL,
    [usp_rpt_filter]                   INT              NOT NULL,
    [usp_rpt_cat]                      BIT              NOT NULL,
    [usp_rpt_rdl_map]                  BIT              NOT NULL,
    [usp_rpt_design]                   BIT              NOT NULL,
    [usp_admin_users]                  BIT              NOT NULL,
    [usp_admin_roles]                  BIT              NOT NULL,
    [usp_admin_skills]                 BIT              NOT NULL,
    [usp_admin_campaigns]              BIT              NOT NULL,
    [usp_admin_gal]                    BIT              NOT NULL,
    [usp_admin_act_status]             BIT              NOT NULL,
    [usp_admin_emails]                 BIT              NOT NULL,
    [usp_admin_posts]                  BIT              NOT NULL,
    [usp_admin_prioritization]         BIT              NOT NULL,
    [usp_admin_quick_links]            BIT              NOT NULL,
    [usp_admin_retntions]              BIT              NOT NULL,
    [usp_admin_alerts]                 BIT              CONSTRAINT [DF_User_Permissions_usp_admin_alerts] DEFAULT ((0)) NULL,
    [usp_acct_retention_view]          INT              CONSTRAINT [DF_user_permissions_usp_acct_retention_view] DEFAULT ((0)) NULL,
    [usp_acct_reassigncsr]             BIT              CONSTRAINT [DF_user_permissions_usp_acct_reassigncsr_1] DEFAULT ((0)) NULL,
    [usp_acct_reassignstatus]          BIT              NULL,
    [usp_acct_reassign_ta]             BIT              NOT NULL,
    [usp_acct__changeownership]        BIT              CONSTRAINT [DF__user_perm__usp_a__03923C47] DEFAULT ((0)) NULL,
    [usp_acct_CampaignOverride]        BIT              CONSTRAINT [DF_user_permissions_usp_acct_CampaignOverride] DEFAULT ((0)) NULL,
    [usp_admin_status_restriction]     BIT              CONSTRAINT [DF_user_permissions_usp_admin_status_restriction] DEFAULT ((0)) NULL,
    [usp_account_status_restriction]   BIT              NULL,
    [usp_admin_manage_duplicate_rules] BIT              CONSTRAINT [DF__user_perm__usp_a__0E240DFC] DEFAULT ((1)) NULL,
    [usp_admin_view_duplicates]        BIT              CONSTRAINT [DF__user_perm__usp_a__0F183235] DEFAULT ((1)) NULL,
    [usp_edit_external_agent]          BIT              NULL,
    [usp_acct_nextacc_settings]        INT              NULL,
    [usp_admin_dashboard]              BIT              CONSTRAINT [DF__user_perm__usp_a__2779CBAB] DEFAULT ((0)) NULL,
    [usp_modify_carrier_issue]         BIT              CONSTRAINT [DF__user_perm__usp_m__2D32A501] DEFAULT ((0)) NULL,
    [usp_dash_type]                    TINYINT          CONSTRAINT [DF__user_perm__usp_d__2F1AED73] DEFAULT ((1)) NULL,
    [usp_edit_submit_enroll_dates]     BIT              CONSTRAINT [DF__user_perm__usp_e__61A66D40] DEFAULT ((0)) NULL,
    [usp_admin_reassignments]          BIT              DEFAULT ((0)) NULL,
    [usp_acct_reassignment_view]       INT              DEFAULT ((0)) NULL,
    [usp_acct_ob]                      BIT              DEFAULT ((0)) NULL,
    [usp_acct_ap]                      BIT              DEFAULT ((0)) NULL,
    [usp_admin_ou]                     BIT              DEFAULT ((0)) NULL,
    CONSTRAINT [PK_User_Permissions] PRIMARY KEY CLUSTERED ([usp_key] ASC),
    CONSTRAINT [FK_User_Permissions_Roles] FOREIGN KEY ([usp_rol_key]) REFERENCES [dbo].[roles] ([rol_key]),
    CONSTRAINT [FK_User_Permissions_Users] FOREIGN KEY ([usp_usr_key]) REFERENCES [dbo].[users] ([usr_key]) ON UPDATE CASCADE
);

