CREATE TABLE [dbo].[users] (
    [usr_key]                             UNIQUEIDENTIFIER NOT NULL,
    [usr_first_name]                      NVARCHAR (200)   NOT NULL,
    [usr_last_name]                       NVARCHAR (200)   NOT NULL,
    [usr_email]                           NVARCHAR (200)   NOT NULL,
    [usr_work_phone]                      NVARCHAR (50)    NOT NULL,
    [usr_work_phone_ext]                  NVARCHAR (25)    NULL,
    [usr_mobile_phone]                    NVARCHAR (50)    NULL,
    [usr_fax]                             NVARCHAR (50)    NULL,
    [usr_other_phone]                     NVARCHAR (50)    NULL,
    [usr_other_phone_ext]                 NVARCHAR (25)    NULL,
    [usr_position]                        NVARCHAR (75)    NULL,
    [usr_note]                            NVARCHAR (200)   NULL,
    [usr_softphone_sq_personal]           NVARCHAR (100)   NOT NULL,
    [usr_softphone_sq_general]            NVARCHAR (100)   NOT NULL,
    [usr_softphone_cm_personal]           NVARCHAR (100)   NULL,
    [usr_softphone_cm_general]            NVARCHAR (100)   NULL,
    [usr_custom1]                         NVARCHAR (200)   NULL,
    [usr_custom2]                         NVARCHAR (200)   NULL,
    [usr_custom3]                         NVARCHAR (200)   NULL,
    [usr_custom4]                         NVARCHAR (200)   NULL,
    [usr_default_cal_view]                BIT              CONSTRAINT [DF_dbo_Users_usr_default_cal_view] DEFAULT ((1)) NOT NULL,
    [usr_cal_background_highlights]       BIT              CONSTRAINT [DF_dbo_Users_usr_cal_background_highlights] DEFAULT ((1)) NULL,
    [usr_new_lead_bold]                   BIT              CONSTRAINT [DF_dbo_Users_usr_new_lead_bold] DEFAULT ((0)) NULL,
    [usr_new_lead_hl]                     BIT              CONSTRAINT [DF_dbo_Users_usr_new_lead_hl] DEFAULT ((0)) NULL,
    [usr_new_lead_hl_incl_newly_assigned] BIT              CONSTRAINT [DF_dbo_Users_usr_new_lead_hl_incl_newly_assigned] DEFAULT ((0)) NULL,
    [usr_flagged_lead_highlight]          BIT              CONSTRAINT [DF_dbo_Users_usr_flagged_lead_highlight] DEFAULT ((0)) NULL,
    [usr_auto_refresh]                    INT              CONSTRAINT [DF_dbo_Users_usr_auto_refresh] DEFAULT ((0)) NULL,
    [usr_save_filter_criteria]            BIT              NULL,
    [usr_login_landing_page]              SMALLINT         NOT NULL,
    [usr_cal_start_hour]                  TINYINT          CONSTRAINT [DF_dbo_Users_usr_cal_start_hour] DEFAULT ((8)) NULL,
    [usr_cal_start_am]                    BIT              CONSTRAINT [DF_dbo_Users_usr_cal_start_am] DEFAULT ((1)) NULL,
    [usr_cal_end_hour]                    TINYINT          CONSTRAINT [DF_dbo_Users_usr_cal_end_hour] DEFAULT ((5)) NULL,
    [usr_cal_end_am]                      BIT              CONSTRAINT [DF_dbo_Users_usr_cal_end_am] DEFAULT ((0)) NULL,
    [usr_mobile_email]                    NVARCHAR (200)   NULL,
    [usr_tz]                              TINYINT          NULL,
    [usr_retention_flag]                  BIT              CONSTRAINT [DF__users__usr_reten__6F0B5556] DEFAULT ((0)) NULL,
    [usr_csr_flag]                        BIT              NULL,
    [usr_transfer_flag]                   BIT              NULL,
    [usr_alternate_product_flag]          BIT              CONSTRAINT [DF__users__usr_alter__7C104AB9] DEFAULT ((0)) NULL,
    [usr_onboard_flag]                    BIT              CONSTRAINT [DF__users__usr_onboa__7B1C2680] DEFAULT ((0)) NULL,
    [usr_net_login]                       NVARCHAR (100)   NULL,
    [usr_pwd]                             NVARCHAR (256)   NULL,
    [usr_reassignment_flag]               BIT              CONSTRAINT [DF__users__usr_reass__4218B34E] DEFAULT ((0)) NULL,
    [usr_arc_id]                          NVARCHAR (25)    NULL,
    [usr_acdcap]                          INT              NULL,
    [usr_api_flag]                        BIT              CONSTRAINT [DF_users_usr_api_flag] DEFAULT ((0)) NULL,
    [usr_acd_flag]                        BIT              CONSTRAINT [DF__users__usr_acd_f__59BB32B5] DEFAULT ((1)) NULL,
    [usr_acd_status_flag]                 BIT              CONSTRAINT [DF__users__usr_acd_s__5AAF56EE] DEFAULT ((0)) NULL,
    [usr_acd_cap_flag]                    BIT              CONSTRAINT [DF__users__usr_acd_c__60683044] DEFAULT ((1)) NULL,
    [usr_phone_system_username]           NVARCHAR (200)   NULL,
    [usr_phone_system_password]           NVARCHAR (200)   NULL,
    [usr_phone_system_id]                 NVARCHAR (200)   NULL,
    [usr_phone_system_stationid]          NVARCHAR (50)    NULL,
    [usr_phone_system_station_type]       NVARCHAR (50)    NULL,
    [usr_phone_system_inbound_skill]      NVARCHAR (200)   NULL,
    [usr_active_flag]                     BIT              CONSTRAINT [DF_dbo_Users_usr_active_flag] DEFAULT ((1)) NULL,
    [usr_delete_flag]                     BIT              CONSTRAINT [DF_dbo_Users_usr_delete_flag] DEFAULT ((0)) NULL,
    [usr_add_usr]                         NVARCHAR (50)    CONSTRAINT [DF_dbo_Users_usr_add_usr] DEFAULT ((0)) NULL,
    [usr_add_date]                        SMALLDATETIME    NULL,
    [usr_change_user]                     NVARCHAR (50)    NULL,
    [usr_change_date]                     SMALLDATETIME    NULL,
    [usr_phone_system_inbound_skillId]    VARCHAR (10)     NULL,
    [usr_cisco_domain_address]            VARCHAR (50)     NULL,
    [usr_cisco_first_name]                VARCHAR (50)     NULL,
    [usr_cisco_last_name]                 VARCHAR (50)     NULL,
    [usr_cisco_agent_id]                  VARCHAR (50)     NULL,
    [usr_cisco_agent_password]            VARCHAR (50)     NULL,
    [usr_cisco_agent_extension1]          VARCHAR (50)     NULL,
    [usr_cisco_agent_extension2]          VARCHAR (50)     NULL,
    [usr_phone_system]                    VARCHAR (50)     NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([usr_key] ASC),
    CONSTRAINT [FK__users__usr_tz__33807B34] FOREIGN KEY ([usr_tz]) REFERENCES [dbo].[timezones] ([tz_key])
);

