//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR_Engine
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    //using System.Data.Objects;
    using System.Data.Entity.Core.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SignalREntities : DbContext
    {
        public SignalREntities()
            : base("name=SignalREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<users> users { get; set; }
        public DbSet<SignalR_Bindings> SignalR_Central_Bindings { get; set; }
        public DbSet<gal_login_acd_statistics> gal_login_acd_statistics { get; set; }
    
        public virtual ObjectResult<LeadBasicDisplayAllAgents_Result> LeadBasicDisplayAllAgents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LeadBasicDisplayAllAgents_Result>("LeadBasicDisplayAllAgents");
        }
    
        public virtual int GetACDStatistics()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetACDStatistics");
        }
    }
}
