//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR_Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignalR_GWB_Bindings
    {
        public string Token { get; set; }
        public string UserKey { get; set; }
        public string ConnectionID { get; set; }
        public Nullable<System.DateTime> ConnectedTime { get; set; }
        public Nullable<System.DateTime> DisconnectedTime { get; set; }
    }
}
