//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalR_Engine
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public System.Guid usr_key { get; set; }
        public string usr_first_name { get; set; }
        public string usr_last_name { get; set; }
        public string usr_email { get; set; }
        public string usr_work_phone { get; set; }
        public string usr_work_phone_ext { get; set; }
        public string usr_mobile_phone { get; set; }
        public string usr_fax { get; set; }
        public string usr_other_phone { get; set; }
        public string usr_other_phone_ext { get; set; }
        public string usr_position { get; set; }
        public string usr_note { get; set; }
        public string usr_softphone_sq_personal { get; set; }
        public string usr_softphone_sq_general { get; set; }
        public string usr_softphone_cm_personal { get; set; }
        public string usr_softphone_cm_general { get; set; }
        public string usr_custom1 { get; set; }
        public string usr_custom2 { get; set; }
        public string usr_custom3 { get; set; }
        public string usr_custom4 { get; set; }
        public bool usr_default_cal_view { get; set; }
        public Nullable<bool> usr_cal_background_highlights { get; set; }
        public Nullable<bool> usr_new_lead_bold { get; set; }
        public Nullable<bool> usr_new_lead_hl { get; set; }
        public Nullable<bool> usr_new_lead_hl_incl_newly_assigned { get; set; }
        public Nullable<bool> usr_flagged_lead_highlight { get; set; }
        public Nullable<int> usr_auto_refresh { get; set; }
        public Nullable<bool> usr_save_filter_criteria { get; set; }
        public short usr_login_landing_page { get; set; }
        public Nullable<byte> usr_cal_start_hour { get; set; }
        public Nullable<bool> usr_cal_start_am { get; set; }
        public Nullable<byte> usr_cal_end_hour { get; set; }
        public Nullable<bool> usr_cal_end_am { get; set; }
        public string usr_mobile_email { get; set; }
        public Nullable<byte> usr_tz { get; set; }
        public Nullable<bool> usr_retention_flag { get; set; }
        public Nullable<bool> usr_csr_flag { get; set; }
        public Nullable<bool> usr_transfer_flag { get; set; }
        public Nullable<bool> usr_alternate_product_flag { get; set; }
        public Nullable<bool> usr_onboard_flag { get; set; }
        public string usr_net_login { get; set; }
        public string usr_pwd { get; set; }
        public Nullable<bool> usr_reassignment_flag { get; set; }
        public string usr_arc_id { get; set; }
        public Nullable<int> usr_acdcap { get; set; }
        public Nullable<bool> usr_api_flag { get; set; }
        public Nullable<bool> usr_acd_flag { get; set; }
        public Nullable<bool> usr_acd_status_flag { get; set; }
        public Nullable<bool> usr_acd_cap_flag { get; set; }
        public string usr_phone_system_username { get; set; }
        public string usr_phone_system_password { get; set; }
        public string usr_phone_system_id { get; set; }
        public string usr_phone_system_stationid { get; set; }
        public string usr_phone_system_station_type { get; set; }
        public string usr_phone_system_inbound_skill { get; set; }
        public Nullable<bool> usr_active_flag { get; set; }
        public Nullable<bool> usr_delete_flag { get; set; }
        public string usr_add_usr { get; set; }
        public Nullable<System.DateTime> usr_add_date { get; set; }
        public string usr_change_user { get; set; }
        public Nullable<System.DateTime> usr_change_date { get; set; }
        public string usr_phone_system_inbound_skillId { get; set; }
        public string usr_phone_system { get; set; }
        public string usr_cisco_domain_address { get; set; }
        public string usr_cisco_first_name { get; set; }
        public string usr_cisco_last_name { get; set; }
        public string usr_cisco_agent_id { get; set; }
        public string usr_cisco_agent_password { get; set; }
        public string usr_cisco_agent_extension1 { get; set; }
        public string usr_cisco_agent_extension2 { get; set; }
    }
}
