//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OLEBridge.SelectCare {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SelectCare.SelectCareSoap")]
    public interface SelectCareSoap {
        
        // CODEGEN: Generating message contract since element name GetIndividualForArcResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIndividualForArc", ReplyAction="*")]
        OLEBridge.SelectCare.GetIndividualForArcResponse GetIndividualForArc(OLEBridge.SelectCare.GetIndividualForArcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIndividualForArc", ReplyAction="*")]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.GetIndividualForArcResponse> GetIndividualForArcAsync(OLEBridge.SelectCare.GetIndividualForArcRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WriteAccountLog", ReplyAction="*")]
        OLEBridge.SelectCare.WriteAccountLogResponse WriteAccountLog(OLEBridge.SelectCare.WriteAccountLogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WriteAccountLog", ReplyAction="*")]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.WriteAccountLogResponse> WriteAccountLogAsync(OLEBridge.SelectCare.WriteAccountLogRequest request);
        
        // CODEGEN: Generating message contract since element name fname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsDataSame", ReplyAction="*")]
        OLEBridge.SelectCare.IsDataSameResponse IsDataSame(OLEBridge.SelectCare.IsDataSameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsDataSame", ReplyAction="*")]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.IsDataSameResponse> IsDataSameAsync(OLEBridge.SelectCare.IsDataSameRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsDataValid", ReplyAction="*")]
        OLEBridge.SelectCare.IsDataValidResponse IsDataValid(OLEBridge.SelectCare.IsDataValidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsDataValid", ReplyAction="*")]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.IsDataValidResponse> IsDataValidAsync(OLEBridge.SelectCare.IsDataValidRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDataForArc", ReplyAction="*")]
        OLEBridge.SelectCare.SaveDataForArcResponse SaveDataForArc(OLEBridge.SelectCare.SaveDataForArcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDataForArc", ReplyAction="*")]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.SaveDataForArcResponse> SaveDataForArcAsync(OLEBridge.SelectCare.SaveDataForArcRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        OLEBridge.SelectCare.AuthenticateUserResponse AuthenticateUser(OLEBridge.SelectCare.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.AuthenticateUserResponse> AuthenticateUserAsync(OLEBridge.SelectCare.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since element name GetUserNameResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserName", ReplyAction="*")]
        OLEBridge.SelectCare.GetUserNameResponse GetUserName(OLEBridge.SelectCare.GetUserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.GetUserNameResponse> GetUserNameAsync(OLEBridge.SelectCare.GetUserNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndividualForArcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndividualForArc", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.GetIndividualForArcRequestBody Body;
        
        public GetIndividualForArcRequest() {
        }
        
        public GetIndividualForArcRequest(OLEBridge.SelectCare.GetIndividualForArcRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIndividualForArcRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public GetIndividualForArcRequestBody() {
        }
        
        public GetIndividualForArcRequestBody(long id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIndividualForArcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIndividualForArcResponse", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.GetIndividualForArcResponseBody Body;
        
        public GetIndividualForArcResponse() {
        }
        
        public GetIndividualForArcResponse(OLEBridge.SelectCare.GetIndividualForArcResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIndividualForArcResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetIndividualForArcResult;
        
        public GetIndividualForArcResponseBody() {
        }
        
        public GetIndividualForArcResponseBody(string GetIndividualForArcResult) {
            this.GetIndividualForArcResult = GetIndividualForArcResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteAccountLogRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteAccountLog", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.WriteAccountLogRequestBody Body;
        
        public WriteAccountLogRequest() {
        }
        
        public WriteAccountLogRequest(OLEBridge.SelectCare.WriteAccountLogRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WriteAccountLogRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        public WriteAccountLogRequestBody() {
        }
        
        public WriteAccountLogRequestBody(long id, string userId, string message) {
            this.id = id;
            this.userId = userId;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WriteAccountLogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WriteAccountLogResponse", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.WriteAccountLogResponseBody Body;
        
        public WriteAccountLogResponse() {
        }
        
        public WriteAccountLogResponse(OLEBridge.SelectCare.WriteAccountLogResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class WriteAccountLogResponseBody {
        
        public WriteAccountLogResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsDataSameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsDataSame", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.IsDataSameRequestBody Body;
        
        public IsDataSameRequest() {
        }
        
        public IsDataSameRequest(OLEBridge.SelectCare.IsDataSameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsDataSameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dob;
        
        public IsDataSameRequestBody() {
        }
        
        public IsDataSameRequestBody(long id, string fname, string lname, string gender, string state, string dob) {
            this.id = id;
            this.fname = fname;
            this.lname = lname;
            this.gender = gender;
            this.state = state;
            this.dob = dob;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsDataSameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsDataSameResponse", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.IsDataSameResponseBody Body;
        
        public IsDataSameResponse() {
        }
        
        public IsDataSameResponse(OLEBridge.SelectCare.IsDataSameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsDataSameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IsDataSameResult;
        
        public IsDataSameResponseBody() {
        }
        
        public IsDataSameResponseBody(string IsDataSameResult) {
            this.IsDataSameResult = IsDataSameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsDataValidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsDataValid", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.IsDataValidRequestBody Body;
        
        public IsDataValidRequest() {
        }
        
        public IsDataValidRequest(OLEBridge.SelectCare.IsDataValidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsDataValidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dob;
        
        public IsDataValidRequestBody() {
        }
        
        public IsDataValidRequestBody(string id, string fname, string lname, string gender, string state, string dob) {
            this.id = id;
            this.fname = fname;
            this.lname = lname;
            this.gender = gender;
            this.state = state;
            this.dob = dob;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsDataValidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsDataValidResponse", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.IsDataValidResponseBody Body;
        
        public IsDataValidResponse() {
        }
        
        public IsDataValidResponse(OLEBridge.SelectCare.IsDataValidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsDataValidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IsDataValidResult;
        
        public IsDataValidResponseBody() {
        }
        
        public IsDataValidResponseBody(string IsDataValidResult) {
            this.IsDataValidResult = IsDataValidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDataForArcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDataForArc", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.SaveDataForArcRequestBody Body;
        
        public SaveDataForArcRequest() {
        }
        
        public SaveDataForArcRequest(OLEBridge.SelectCare.SaveDataForArcRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDataForArcRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string appState;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string dob;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string mName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string dayPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string evenPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string cellPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool emailOptOut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string address1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string address2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string state;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string zipCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string appDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string parentActId;
        
        public SaveDataForArcRequestBody() {
        }
        
        public SaveDataForArcRequestBody(
                    string id, 
                    string fname, 
                    string lname, 
                    string gender, 
                    string appState, 
                    string dob, 
                    string mName, 
                    string dayPhone, 
                    string evenPhone, 
                    string cellPhone, 
                    string email, 
                    bool emailOptOut, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zipCode, 
                    string appDate, 
                    string parentActId) {
            this.id = id;
            this.fname = fname;
            this.lname = lname;
            this.gender = gender;
            this.appState = appState;
            this.dob = dob;
            this.mName = mName;
            this.dayPhone = dayPhone;
            this.evenPhone = evenPhone;
            this.cellPhone = cellPhone;
            this.email = email;
            this.emailOptOut = emailOptOut;
            this.address1 = address1;
            this.address2 = address2;
            this.city = city;
            this.state = state;
            this.zipCode = zipCode;
            this.appDate = appDate;
            this.parentActId = parentActId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDataForArcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDataForArcResponse", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.SaveDataForArcResponseBody Body;
        
        public SaveDataForArcResponse() {
        }
        
        public SaveDataForArcResponse(OLEBridge.SelectCare.SaveDataForArcResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDataForArcResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveDataForArcResult;
        
        public SaveDataForArcResponseBody() {
        }
        
        public SaveDataForArcResponseBody(string SaveDataForArcResult) {
            this.SaveDataForArcResult = SaveDataForArcResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(OLEBridge.SelectCare.AuthenticateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pwd;
        
        public AuthenticateUserRequestBody() {
        }
        
        public AuthenticateUserRequestBody(string user, string pwd) {
            this.user = user;
            this.pwd = pwd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(OLEBridge.SelectCare.AuthenticateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid AuthenticateUserResult;
        
        public AuthenticateUserResponseBody() {
        }
        
        public AuthenticateUserResponseBody(System.Guid AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserName", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.GetUserNameRequestBody Body;
        
        public GetUserNameRequest() {
        }
        
        public GetUserNameRequest(OLEBridge.SelectCare.GetUserNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid key;
        
        public GetUserNameRequestBody() {
        }
        
        public GetUserNameRequestBody(System.Guid key) {
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public OLEBridge.SelectCare.GetUserNameResponseBody Body;
        
        public GetUserNameResponse() {
        }
        
        public GetUserNameResponse(OLEBridge.SelectCare.GetUserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserNameResult;
        
        public GetUserNameResponseBody() {
        }
        
        public GetUserNameResponseBody(string GetUserNameResult) {
            this.GetUserNameResult = GetUserNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SelectCareSoapChannel : OLEBridge.SelectCare.SelectCareSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SelectCareSoapClient : System.ServiceModel.ClientBase<OLEBridge.SelectCare.SelectCareSoap>, OLEBridge.SelectCare.SelectCareSoap {
        
        public SelectCareSoapClient() {
        }
        
        public SelectCareSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SelectCareSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelectCareSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SelectCareSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OLEBridge.SelectCare.GetIndividualForArcResponse OLEBridge.SelectCare.SelectCareSoap.GetIndividualForArc(OLEBridge.SelectCare.GetIndividualForArcRequest request) {
            return base.Channel.GetIndividualForArc(request);
        }
        
        public string GetIndividualForArc(long id) {
            OLEBridge.SelectCare.GetIndividualForArcRequest inValue = new OLEBridge.SelectCare.GetIndividualForArcRequest();
            inValue.Body = new OLEBridge.SelectCare.GetIndividualForArcRequestBody();
            inValue.Body.id = id;
            OLEBridge.SelectCare.GetIndividualForArcResponse retVal = ((OLEBridge.SelectCare.SelectCareSoap)(this)).GetIndividualForArc(inValue);
            return retVal.Body.GetIndividualForArcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.GetIndividualForArcResponse> OLEBridge.SelectCare.SelectCareSoap.GetIndividualForArcAsync(OLEBridge.SelectCare.GetIndividualForArcRequest request) {
            return base.Channel.GetIndividualForArcAsync(request);
        }
        
        public System.Threading.Tasks.Task<OLEBridge.SelectCare.GetIndividualForArcResponse> GetIndividualForArcAsync(long id) {
            OLEBridge.SelectCare.GetIndividualForArcRequest inValue = new OLEBridge.SelectCare.GetIndividualForArcRequest();
            inValue.Body = new OLEBridge.SelectCare.GetIndividualForArcRequestBody();
            inValue.Body.id = id;
            return ((OLEBridge.SelectCare.SelectCareSoap)(this)).GetIndividualForArcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OLEBridge.SelectCare.WriteAccountLogResponse OLEBridge.SelectCare.SelectCareSoap.WriteAccountLog(OLEBridge.SelectCare.WriteAccountLogRequest request) {
            return base.Channel.WriteAccountLog(request);
        }
        
        public void WriteAccountLog(long id, string userId, string message) {
            OLEBridge.SelectCare.WriteAccountLogRequest inValue = new OLEBridge.SelectCare.WriteAccountLogRequest();
            inValue.Body = new OLEBridge.SelectCare.WriteAccountLogRequestBody();
            inValue.Body.id = id;
            inValue.Body.userId = userId;
            inValue.Body.message = message;
            OLEBridge.SelectCare.WriteAccountLogResponse retVal = ((OLEBridge.SelectCare.SelectCareSoap)(this)).WriteAccountLog(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.WriteAccountLogResponse> OLEBridge.SelectCare.SelectCareSoap.WriteAccountLogAsync(OLEBridge.SelectCare.WriteAccountLogRequest request) {
            return base.Channel.WriteAccountLogAsync(request);
        }
        
        public System.Threading.Tasks.Task<OLEBridge.SelectCare.WriteAccountLogResponse> WriteAccountLogAsync(long id, string userId, string message) {
            OLEBridge.SelectCare.WriteAccountLogRequest inValue = new OLEBridge.SelectCare.WriteAccountLogRequest();
            inValue.Body = new OLEBridge.SelectCare.WriteAccountLogRequestBody();
            inValue.Body.id = id;
            inValue.Body.userId = userId;
            inValue.Body.message = message;
            return ((OLEBridge.SelectCare.SelectCareSoap)(this)).WriteAccountLogAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OLEBridge.SelectCare.IsDataSameResponse OLEBridge.SelectCare.SelectCareSoap.IsDataSame(OLEBridge.SelectCare.IsDataSameRequest request) {
            return base.Channel.IsDataSame(request);
        }
        
        public string IsDataSame(long id, string fname, string lname, string gender, string state, string dob) {
            OLEBridge.SelectCare.IsDataSameRequest inValue = new OLEBridge.SelectCare.IsDataSameRequest();
            inValue.Body = new OLEBridge.SelectCare.IsDataSameRequestBody();
            inValue.Body.id = id;
            inValue.Body.fname = fname;
            inValue.Body.lname = lname;
            inValue.Body.gender = gender;
            inValue.Body.state = state;
            inValue.Body.dob = dob;
            OLEBridge.SelectCare.IsDataSameResponse retVal = ((OLEBridge.SelectCare.SelectCareSoap)(this)).IsDataSame(inValue);
            return retVal.Body.IsDataSameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.IsDataSameResponse> OLEBridge.SelectCare.SelectCareSoap.IsDataSameAsync(OLEBridge.SelectCare.IsDataSameRequest request) {
            return base.Channel.IsDataSameAsync(request);
        }
        
        public System.Threading.Tasks.Task<OLEBridge.SelectCare.IsDataSameResponse> IsDataSameAsync(long id, string fname, string lname, string gender, string state, string dob) {
            OLEBridge.SelectCare.IsDataSameRequest inValue = new OLEBridge.SelectCare.IsDataSameRequest();
            inValue.Body = new OLEBridge.SelectCare.IsDataSameRequestBody();
            inValue.Body.id = id;
            inValue.Body.fname = fname;
            inValue.Body.lname = lname;
            inValue.Body.gender = gender;
            inValue.Body.state = state;
            inValue.Body.dob = dob;
            return ((OLEBridge.SelectCare.SelectCareSoap)(this)).IsDataSameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OLEBridge.SelectCare.IsDataValidResponse OLEBridge.SelectCare.SelectCareSoap.IsDataValid(OLEBridge.SelectCare.IsDataValidRequest request) {
            return base.Channel.IsDataValid(request);
        }
        
        public string IsDataValid(string id, string fname, string lname, string gender, string state, string dob) {
            OLEBridge.SelectCare.IsDataValidRequest inValue = new OLEBridge.SelectCare.IsDataValidRequest();
            inValue.Body = new OLEBridge.SelectCare.IsDataValidRequestBody();
            inValue.Body.id = id;
            inValue.Body.fname = fname;
            inValue.Body.lname = lname;
            inValue.Body.gender = gender;
            inValue.Body.state = state;
            inValue.Body.dob = dob;
            OLEBridge.SelectCare.IsDataValidResponse retVal = ((OLEBridge.SelectCare.SelectCareSoap)(this)).IsDataValid(inValue);
            return retVal.Body.IsDataValidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.IsDataValidResponse> OLEBridge.SelectCare.SelectCareSoap.IsDataValidAsync(OLEBridge.SelectCare.IsDataValidRequest request) {
            return base.Channel.IsDataValidAsync(request);
        }
        
        public System.Threading.Tasks.Task<OLEBridge.SelectCare.IsDataValidResponse> IsDataValidAsync(string id, string fname, string lname, string gender, string state, string dob) {
            OLEBridge.SelectCare.IsDataValidRequest inValue = new OLEBridge.SelectCare.IsDataValidRequest();
            inValue.Body = new OLEBridge.SelectCare.IsDataValidRequestBody();
            inValue.Body.id = id;
            inValue.Body.fname = fname;
            inValue.Body.lname = lname;
            inValue.Body.gender = gender;
            inValue.Body.state = state;
            inValue.Body.dob = dob;
            return ((OLEBridge.SelectCare.SelectCareSoap)(this)).IsDataValidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OLEBridge.SelectCare.SaveDataForArcResponse OLEBridge.SelectCare.SelectCareSoap.SaveDataForArc(OLEBridge.SelectCare.SaveDataForArcRequest request) {
            return base.Channel.SaveDataForArc(request);
        }
        
        public string SaveDataForArc(
                    string id, 
                    string fname, 
                    string lname, 
                    string gender, 
                    string appState, 
                    string dob, 
                    string mName, 
                    string dayPhone, 
                    string evenPhone, 
                    string cellPhone, 
                    string email, 
                    bool emailOptOut, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zipCode, 
                    string appDate, 
                    string parentActId) {
            OLEBridge.SelectCare.SaveDataForArcRequest inValue = new OLEBridge.SelectCare.SaveDataForArcRequest();
            inValue.Body = new OLEBridge.SelectCare.SaveDataForArcRequestBody();
            inValue.Body.id = id;
            inValue.Body.fname = fname;
            inValue.Body.lname = lname;
            inValue.Body.gender = gender;
            inValue.Body.appState = appState;
            inValue.Body.dob = dob;
            inValue.Body.mName = mName;
            inValue.Body.dayPhone = dayPhone;
            inValue.Body.evenPhone = evenPhone;
            inValue.Body.cellPhone = cellPhone;
            inValue.Body.email = email;
            inValue.Body.emailOptOut = emailOptOut;
            inValue.Body.address1 = address1;
            inValue.Body.address2 = address2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zipCode = zipCode;
            inValue.Body.appDate = appDate;
            inValue.Body.parentActId = parentActId;
            OLEBridge.SelectCare.SaveDataForArcResponse retVal = ((OLEBridge.SelectCare.SelectCareSoap)(this)).SaveDataForArc(inValue);
            return retVal.Body.SaveDataForArcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.SaveDataForArcResponse> OLEBridge.SelectCare.SelectCareSoap.SaveDataForArcAsync(OLEBridge.SelectCare.SaveDataForArcRequest request) {
            return base.Channel.SaveDataForArcAsync(request);
        }
        
        public System.Threading.Tasks.Task<OLEBridge.SelectCare.SaveDataForArcResponse> SaveDataForArcAsync(
                    string id, 
                    string fname, 
                    string lname, 
                    string gender, 
                    string appState, 
                    string dob, 
                    string mName, 
                    string dayPhone, 
                    string evenPhone, 
                    string cellPhone, 
                    string email, 
                    bool emailOptOut, 
                    string address1, 
                    string address2, 
                    string city, 
                    string state, 
                    string zipCode, 
                    string appDate, 
                    string parentActId) {
            OLEBridge.SelectCare.SaveDataForArcRequest inValue = new OLEBridge.SelectCare.SaveDataForArcRequest();
            inValue.Body = new OLEBridge.SelectCare.SaveDataForArcRequestBody();
            inValue.Body.id = id;
            inValue.Body.fname = fname;
            inValue.Body.lname = lname;
            inValue.Body.gender = gender;
            inValue.Body.appState = appState;
            inValue.Body.dob = dob;
            inValue.Body.mName = mName;
            inValue.Body.dayPhone = dayPhone;
            inValue.Body.evenPhone = evenPhone;
            inValue.Body.cellPhone = cellPhone;
            inValue.Body.email = email;
            inValue.Body.emailOptOut = emailOptOut;
            inValue.Body.address1 = address1;
            inValue.Body.address2 = address2;
            inValue.Body.city = city;
            inValue.Body.state = state;
            inValue.Body.zipCode = zipCode;
            inValue.Body.appDate = appDate;
            inValue.Body.parentActId = parentActId;
            return ((OLEBridge.SelectCare.SelectCareSoap)(this)).SaveDataForArcAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OLEBridge.SelectCare.AuthenticateUserResponse OLEBridge.SelectCare.SelectCareSoap.AuthenticateUser(OLEBridge.SelectCare.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public System.Guid AuthenticateUser(string user, string pwd) {
            OLEBridge.SelectCare.AuthenticateUserRequest inValue = new OLEBridge.SelectCare.AuthenticateUserRequest();
            inValue.Body = new OLEBridge.SelectCare.AuthenticateUserRequestBody();
            inValue.Body.user = user;
            inValue.Body.pwd = pwd;
            OLEBridge.SelectCare.AuthenticateUserResponse retVal = ((OLEBridge.SelectCare.SelectCareSoap)(this)).AuthenticateUser(inValue);
            return retVal.Body.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.AuthenticateUserResponse> OLEBridge.SelectCare.SelectCareSoap.AuthenticateUserAsync(OLEBridge.SelectCare.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<OLEBridge.SelectCare.AuthenticateUserResponse> AuthenticateUserAsync(string user, string pwd) {
            OLEBridge.SelectCare.AuthenticateUserRequest inValue = new OLEBridge.SelectCare.AuthenticateUserRequest();
            inValue.Body = new OLEBridge.SelectCare.AuthenticateUserRequestBody();
            inValue.Body.user = user;
            inValue.Body.pwd = pwd;
            return ((OLEBridge.SelectCare.SelectCareSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OLEBridge.SelectCare.GetUserNameResponse OLEBridge.SelectCare.SelectCareSoap.GetUserName(OLEBridge.SelectCare.GetUserNameRequest request) {
            return base.Channel.GetUserName(request);
        }
        
        public string GetUserName(System.Guid key) {
            OLEBridge.SelectCare.GetUserNameRequest inValue = new OLEBridge.SelectCare.GetUserNameRequest();
            inValue.Body = new OLEBridge.SelectCare.GetUserNameRequestBody();
            inValue.Body.key = key;
            OLEBridge.SelectCare.GetUserNameResponse retVal = ((OLEBridge.SelectCare.SelectCareSoap)(this)).GetUserName(inValue);
            return retVal.Body.GetUserNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OLEBridge.SelectCare.GetUserNameResponse> OLEBridge.SelectCare.SelectCareSoap.GetUserNameAsync(OLEBridge.SelectCare.GetUserNameRequest request) {
            return base.Channel.GetUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<OLEBridge.SelectCare.GetUserNameResponse> GetUserNameAsync(System.Guid key) {
            OLEBridge.SelectCare.GetUserNameRequest inValue = new OLEBridge.SelectCare.GetUserNameRequest();
            inValue.Body = new OLEBridge.SelectCare.GetUserNameRequestBody();
            inValue.Body.key = key;
            return ((OLEBridge.SelectCare.SelectCareSoap)(this)).GetUserNameAsync(inValue);
        }
    }
}
