//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALEngine_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationStorage
    {
        public string Key { get; set; }
        public Nullable<int> iValue { get; set; }
        public Nullable<decimal> fValue { get; set; }
        public Nullable<bool> bValue { get; set; }
        public Nullable<System.Guid> uValue { get; set; }
        public Nullable<System.DateTime> dValue { get; set; }
        public string tvalue { get; set; }
    }
}
