//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALEngine_Library
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GALEngineEntities : DbContext
    {
        public GALEngineEntities()
            : base("name=GALEngineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApplicationStorage> Application_Storage { get; set; }
        public DbSet<queueAcdStatistics> queue_acd_statistics { get; set; }
        public DbSet<queueInboundAcd> queue_inbound_acd { get; set; }
        public DbSet<GALEngineListsDump> GALEngineListsDump { get; set; }
    
        public virtual ObjectResult<ACDToDial_Result> ACDToDial(Nullable<System.Guid> agentID)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ACDToDial_Result>("ACDToDial", agentIDParameter);
        }
    
        public virtual int GetACDStatistics()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetACDStatistics");
        }
    
        public virtual int UpdateStatsCallTaken(Nullable<System.Guid> agentID, Nullable<long> acdqueueID)
        {
            var agentIDParameter = agentID.HasValue ?
                new ObjectParameter("agentID", agentID) :
                new ObjectParameter("agentID", typeof(System.Guid));
    
            var acdqueueIDParameter = acdqueueID.HasValue ?
                new ObjectParameter("acdqueueID", acdqueueID) :
                new ObjectParameter("acdqueueID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateStatsCallTaken", agentIDParameter, acdqueueIDParameter);
        }
    
        public virtual ObjectResult<Nullable<System.Guid>> GetAgentListForACDUpdate(Nullable<long> inboundQueueID)
        {
            var inboundQueueIDParameter = inboundQueueID.HasValue ?
                new ObjectParameter("inboundQueueID", inboundQueueID) :
                new ObjectParameter("inboundQueueID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.Guid>>("GetAgentListForACDUpdate", inboundQueueIDParameter);
        }
    
        public virtual ObjectResult<LeadBasicDisplayForAllAgents_Result> LeadBasicDisplayForAllAgents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LeadBasicDisplayForAllAgents_Result>("LeadBasicDisplayForAllAgents");
        }
    }
}
