//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALEngine_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class queueInboundAcd
    {
        public long Key { get; set; }
        public string Skill { get; set; }
        public string ContactID { get; set; }
        public string PhoneMumber { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public string AddUser { get; set; }
        public string ModUser { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> CmpID { get; set; }
        public Nullable<System.Guid> StaKey { get; set; }
        public Nullable<System.Guid> CallTakenBy { get; set; }
        public Nullable<System.DateTime> CallTakenTime { get; set; }
    }
}
