//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GALEngine_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class queueAcdStatistics
    {
        public System.Guid AgentID { get; set; }
        public Nullable<int> AcdCount { get; set; }
        public Nullable<int> MaxAcd { get; set; }
        public Nullable<int> MaxQuota { get; set; }
        public Nullable<int> MinLevel { get; set; }
        public Nullable<int> NextRefresh { get; set; }
        public Nullable<int> AcdCallTaken { get; set; }
        public Nullable<int> PVScheduleResult { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> qas_last_update { get; set; }
    }
}
